name: Flutter SDK for Linux

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]
  schedule:
    # https://crontab.guru/#40_10_*_*_*
    - cron: '40 10 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stable:
    uses: ./.github/workflows/flutter.yml
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 3.27.0
    with:
      runs-on: ubuntu-latest
      version: ${{ matrix.version }}
      channel: stable

  beta:
    uses: ./.github/workflows/flutter.yml
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 3.27.0-0.1.pre
    with:
      runs-on: ubuntu-latest
      version: ${{ matrix.version }}
      channel: beta
